name: Deploy to AWS
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd my-app
            git pull origin main
            docker build -t shahzaman/devops-app:v1 .
            docker rm -f my-site || true
            docker run -d -p 80:80 --name my-site shahzaman/devops-app:v1
